---
layout: cv
title: Seth Polatis's CV
---
# Seth Polatis
Data Scientist, Accountant, Future Auditor
<div id="webaddress">
<a href="seth@polatis.org">seth@polatis.org</a>
| <a href="http://en.wikipedia.org/">My wikipedia page</a>
</div>


## Currently

- Accounting Lab Assistant at Brigham Young Universtiy - Idaho, Rexburg, ID

### Specialized in

- Accounting, Data Science, Computer Information Technology


### Research interests

- Accounting, Data Science, Computer Information Technology


## Education

`January 2025 - December 2025`  
__Utah State University__  
_Master of Accountancy (MAcc)_

`September 2019 - December 2024`  
__Brigham Young University - Idaho__  
_BS in Accounting_  
_Minor in CIT_

## Occupation

`April 2024 - July 2024`  
__Accounting Lab Assistant__, Brigham Young University - Idaho 

- Assist students with financial and managerial accounting concepts

`January 2024 - March 2024`  
__Audit Intern__, Eide Bailly  

- tested and reported findings for Cash, PP&E, and Accounts Payable on 2 audits  
- Complied financial statements according to GAAP for 3 entities

`July 2014 - September 2023`  
__Accounts Payable/ Payroll Specialist / Scale House Operator__, Osgood Grain, Inc.  

- Processed weight of 30 trucks upon entry and exit of facility daily and entered results into Microsoft Excel  
- Evaluated wheat samples from 30 trucks daily for moisture levels and weight per bushel  
- Processed payroll biweekly for all office employees using QuickBooks

<!-- ### Footer

Last updated: May 2024 -->